version: '3.7'
services:
  consul:
    restart: always
    network_mode: host
    image: consul
    command: consul agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level warn
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

#  registrator:
#    restart: always
#    network_mode: host
#    depends_on:
#      - consul
#    image: gliderlabs/registrator:master
#    command: -internal consul://consul:8500
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock
#    links:
#      - consul

